default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shopkeep
  host: localhost
  username: kopeeeman
  password: kopeeeman

test:
  <<: *default
  database: shopkeep_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: shopkeep_production
